# Generated by Django 3.2.8 on 2021-10-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cell_phone',
            field=models.CharField(default='(402)000-0000', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='NE', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
