# Generated by Django 3.2.8 on 2021-10-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_product_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mail_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_name',
        ),
    ]
